// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using getbiz_user_app.Getbiz_DbContext;

namespace getbiz_user_app.Migrations
{
    [DbContext(typeof(UserAppDB_DbContext))]
    partial class UserAppDB_DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("getbiz_user_app.Models.getbiz_app_launch_screen_display", b =>
                {
                    b.Property<int>("user_app_launch_screen_location")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("user_app_id")
                        .HasColumnType("int");

                    b.Property<string>("user_app_launch_screen_desktop_image_path")
                        .HasColumnType("longtext");

                    b.Property<string>("user_app_launch_screen_mobile_image_path")
                        .HasColumnType("longtext");

                    b.Property<string>("user_app_launch_screen_text1")
                        .HasColumnType("longtext");

                    b.Property<string>("user_app_launch_screen_text2")
                        .HasColumnType("longtext");

                    b.Property<string>("user_app_launch_screen_text3")
                        .HasColumnType("longtext");

                    b.HasKey("user_app_launch_screen_location");

                    b.ToTable("getbiz_app_launch_screen_display");
                });

            modelBuilder.Entity("getbiz_user_app.Models.user_app_about_demo", b =>
                {
                    b.Property<int>("user_app_demo_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("user_app_attachments_path")
                        .HasColumnType("longtext");

                    b.Property<string>("user_app_demo_video_path")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("user_app_description_time_stamp")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("user_app_id")
                        .HasColumnType("int");

                    b.Property<string>("user_app_time_stamp_title")
                        .HasColumnType("longtext");

                    b.HasKey("user_app_demo_id");

                    b.ToTable("user_app_about_demo");
                });

            modelBuilder.Entity("getbiz_user_app.Models.user_app_additional_data", b =>
                {
                    b.Property<int>("user_app_additional_data_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("can_this_app_be_displayed_in_customerbizapp_launch_screen")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("can_this_user_app_be_blocked_by_app_administrator")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("does_this_app_have_configuration_data_specific_to_this_app")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("user_app_id")
                        .HasColumnType("int");

                    b.HasKey("user_app_additional_data_id");

                    b.ToTable("user_app_additional_data");
                });

            modelBuilder.Entity("getbiz_user_app.Models.user_app_business_categories", b =>
                {
                    b.Property<int>("user_app_business_category_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("user_app_business_category_name")
                        .HasColumnType("longtext");

                    b.Property<string>("user_app_business_category_path")
                        .HasColumnType("longtext");

                    b.HasKey("user_app_business_category_id");

                    b.ToTable("user_app_business_categories");
                });

            modelBuilder.Entity("getbiz_user_app.Models.user_app_business_category_about_demo", b =>
                {
                    b.Property<int>("user_app_business_category_about_demo_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("user_app_business_category_demo_video_path")
                        .HasColumnType("longtext");

                    b.Property<string>("user_app_business_category_description_time_stamp")
                        .HasColumnType("longtext");

                    b.Property<int>("user_app_business_category_id")
                        .HasColumnType("int");

                    b.HasKey("user_app_business_category_about_demo_id");

                    b.ToTable("user_app_business_category_about_demo");
                });

            modelBuilder.Entity("getbiz_user_app.Models.user_app_categories", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("longtext");

                    b.Property<string>("path")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("user_app_categories");
                });

            modelBuilder.Entity("getbiz_user_app.Models.user_app_cloud_file_storage_permissions", b =>
                {
                    b.Property<int>("user_app_cloud_file_storage_permissions_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("user_app_cloud_file_copy_files")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("user_app_cloud_file_delete_files")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("user_app_cloud_file_delete_folder")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("user_app_cloud_file_storage_permissions_id");

                    b.ToTable("user_app_cloud_file_storage_permissions");
                });

            modelBuilder.Entity("getbiz_user_app.Models.user_app_countries", b =>
                {
                    b.Property<int>("user_app_country_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("user_app_country_name")
                        .HasColumnType("longtext");

                    b.Property<string>("user_app_country_path")
                        .HasColumnType("longtext");

                    b.HasKey("user_app_country_id");

                    b.ToTable("user_app_countries");
                });

            modelBuilder.Entity("getbiz_user_app.Models.user_app_country_business_category_location", b =>
                {
                    b.Property<int>("user_app_country_business_category_location_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<int>("user_app_business_category_id")
                        .HasColumnType("int");

                    b.Property<float>("user_app_category_location")
                        .HasColumnType("float");

                    b.Property<int>("user_app_country_id")
                        .HasColumnType("int");

                    b.Property<int>("user_app_id")
                        .HasColumnType("int");

                    b.HasKey("user_app_country_business_category_location_Id");

                    b.ToTable("user_app_country_business_category_location");
                });

            modelBuilder.Entity("getbiz_user_app.Models.user_app_master", b =>
                {
                    b.Property<int>("user_app_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("user_app_development_status")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("user_app_icon_image")
                        .HasColumnType("longtext");

                    b.Property<string>("user_app_icon_name")
                        .HasColumnType("longtext");

                    b.Property<string>("user_app_web_link")
                        .HasColumnType("longtext");

                    b.HasKey("user_app_id");

                    b.ToTable("user_app_master");
                });

            modelBuilder.Entity("getbiz_user_app.Models.user_app_names", b =>
                {
                    b.Property<int>("user_app_names_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("user_app_icon_image_path")
                        .HasColumnType("longtext");

                    b.Property<string>("user_app_icon_name")
                        .HasColumnType("longtext");

                    b.Property<int>("user_app_id")
                        .HasColumnType("int");

                    b.Property<string>("user_app_name")
                        .HasColumnType("longtext");

                    b.Property<string>("user_app_title_bar_name")
                        .HasColumnType("longtext");

                    b.Property<string>("user_app_web_link")
                        .HasColumnType("longtext");

                    b.HasKey("user_app_names_id");

                    b.ToTable("user_app_names");
                });

            modelBuilder.Entity("getbiz_user_app.Models.user_apps_audit_trail", b =>
                {
                    b.Property<int>("user_app_audit_trail_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("user_app_activity")
                        .HasColumnType("longtext");

                    b.Property<int>("user_app_activity_by_user_id")
                        .HasColumnType("int");

                    b.Property<string>("user_app_activity_time_stamp")
                        .HasColumnType("longtext");

                    b.Property<int>("user_app_id")
                        .HasColumnType("int");

                    b.HasKey("user_app_audit_trail_Id");

                    b.ToTable("user_apps_audit_trail");
                });

            modelBuilder.Entity("getbiz_user_app.Models.user_apps_update_time_stamp", b =>
                {
                    b.Property<int>("user_app_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("user_app_update_time_stamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("user_app_id");

                    b.ToTable("user_apps_update_time_stamp");
                });
#pragma warning restore 612, 618
        }
    }
}
